### ISSUE TITLE
Include Elements

### ISSUE THREAD

**Issue by Giwrgosyea** [5g-empower/empower-lvap-agent#2] opened 2016-11-18 18:02 UTC
I am trying to include some elements (Ethernet, local) ,aside with yours, in your code but when i compile  with Make -j 3 from empower-openwrt i get "undefined reference.." from those included elements. 
Are you enabling your own elements before compiling openwrt ?

**Comment by rriggio** [comment] 2016-11-20 19:14
Could you report the precise list of steps you are doing together with the cull error and the expected result.

**Comment by Giwrgosyea** [comment] 2016-11-21 10:05
I do exactly as you suggest here: https://github.com/5g-empower/5g-empower.github.io/wiki/Setting-up-the-WTP
But inside the code of empower-lvap-agent/elements/empowerlvapmanager.hh , I included those  2 elements( are located in empower-lvap-agent/elements/local and  empower-lvap-agent/elements/ethernet)  and inside empower-lvap-agent/elements/empowerlvapmanager.cc I include some functions from those 2 elements
And i get: 
empowerlvapmanager.cc:(.text+0xa79): undefined reference to `ARPTable::reverse_lookup(EtherAddress const&)'
empowerlvapmanager.cc:(.text+0xa8e): undefined reference to `ARPTable::reverse_lookup(EtherAddress const&)'
empowerlvapmanager.cc:(.text+0xaa8): undefined reference to `TCPDemux::add_flow(IPAddress, unsigned short, IPAddress, unsigned short, unsigned int)'

**Comment by rriggio** [comment] 2016-11-21 15:32
Could you write precisely the changes that you have made? If you follow 
the instructions on that page you clearly need to either change the package
Makefile to point to another git repo containing your changes to the code.

Is this the case? 

Also this is not a bug so I will close the issue and I will invite you to start
a new thread in the mailing list.

R.

**Closed as completed by rriggio** 2016-11-21 15:32 UTC
